src/main.py
from flask import Flask
from config import *

app = Flask(__name__)

@app.route('/')
def main():
    return 'teste'

configure_all(app)

app.run(debug=True)

src/routes/filmes.py
from flask import Blueprint, render_template, request, redirect, url_for
from database.Models.filmes import Filmes

filme_route = Blueprint('filmes', __name__)

"""

##    ROTAS FILMES    ##

/filmes/ (GET) -- lista os filmes
/filmes/ (POST) -- inserir filmes no servidor
/filmes/new/ (GET) -- exibe um formulario para a adição de um novo filme
/filmes/<int:id> (GET) -- exibe dados de um filme em específico
/filmes/<int:id>/edit/ (GET) -- exibe um formulário com os dados do filme selecionado para editar
/filmes/<int:id>/update/ (PUT) -- envia uma atualização do filme para o servidor
/filmes/<int:id>/delete/ (DELETE) -- deleta o filme escolhido do servidor


"""

#rota principal de filmes
@filme_route.route('/')
def index():

    return render_template('index_filmes.html')


#rota para listar os filmes
@filme_route.route('/listar', methods=['GET','POST','PUT','DELETE'])
def listar_filmes():

    filmes = Filmes.select()

    return render_template('listar_filmes.html', filmes = filmes)


#rota para inserir um novo filme no banco de dados    
@filme_route.route('/inserir', methods=['POST'])
def inserir_filmes():
    data = request.json
    Filmes.create(
        filme_nome = data['nome'],
        filme_data = data['data'],
        filme_genero = data['genero'],
        filme_duracao = data['duracao'],
        filme_sinopse = data['sinopse'],
        )
    return redirect(url_for('filmes.listar_filmes'))


#rota para apresentar o formulário de criação de um novo filme 
@filme_route.route("/new")
def form_create_filme():
    return render_template('form_filme.html')


#rota para apresentar os dados do filme escolhido
@filme_route.route("/<int:filme_id>")
def dados_filme():
    return render_template("dados_filme.html")


#rota para apresentar o formulário de edição do filme escolhido
@filme_route.route("/<int:filme_id>/edit")
def form_editar_filme(filme_id):

    filme = Filmes.get_by_id(filme_id)

    return render_template("form_filme.html", filme=filme)


#rota para enviar e atualizar os dados no banco de dados
@filme_route.route("/<int:filme_id>/update", methods=['PUT'])
def update_filme(filme_id):

    data = request.json

    atualiza_filme = Filmes.get_by_id(filme_id)
    atualiza_filme.filme_nome = data['nome']
    atualiza_filme.filme_data = data['data']
    atualiza_filme.filme_genero = data['genero']
    atualiza_filme.filme_duracao = data['duracao']
    atualiza_filme.filme_sinopse = data['sinopse']
    atualiza_filme.save()

    return redirect(url_for('filmes.listar_filmes'))


#rota para deletar o filme escolhido
@filme_route.route("/<int:filme_id>/delete", methods=['DELETE'])
def delete_filme(filme_id):
    filme = Filmes.get_by_id(filme_id)
    filme.delete_instance()
    return {"delete": 'ok'}

src/routes/users.py
from flask import Blueprint, render_template, request, redirect, url_for

user_route = Blueprint('user', __name__)

"""

##    ROTAS USUÁRIOS    ##

/user/ (GET) -- lista os usuários
/user/ (POST) -- inserir um novo usuário no banco de dados
/user/new/ (GET) -- exibe um formulario para a criação de um novo usuário
/users/<int:id> (GET) -- exibe dados de um usuário em específico
/users/<int:id>/edit/ (GET) -- exibe um formulário com os dados do usuário selecionado para editar
/users/<int:id>/update/ (PUT) -- envia uma atualização do usuário para o servidor
/users/<int:id>/delete/ (DELETE) -- deleta o usuário escolhido do servidor

"""

user_route.route('/')
def list_users():
 
    pass

user_route.route('/', methods=['POST'])
def insert_users():
 
    pass

user_route.route('/new')
def form_new_users():
 
    pass

user_route.route('/<int:user_id>')
def show_user():
 
    pass

user_route.route('/<int: user_id>/edit')
def form_edit_users():
 
    pass

user_route.route('/<int: user_id>/update', methods=['PUT'])
def update_user():
 
    pass

user_route.route('/<int: user_id>/delete', methods=['DELETE'])
def delete_user():
 
    pass

src/templates/form_filme.html
<h1>Adicionar Filme</h1>
  <form class="c-form" 
        c-target="#index-filmes"
        
        {% if filme %}

        action="{{ url_for('filmes.update_filme', filme_id=filme.id) }}"
        method="PUT"

        {% else %}

        action="{{ url_for('filmes.inserir_filmes') }}"
        method="POST"

        {% endif %}
        >


    <div class="mb-3" >
      <label class="form-label">Nome do filme</label>
      <input type="text" class="form-control" name="nome" {% if filme %} value="{{filme.filme_nome}}" {% endif %} required>
    </div>


    <div class="mb-3">
      <label class="form-label">Data de lançamento</label>
      <input type="date" class="form-control" name="data" {% if filme %} value="{{filme.filme_data}}" {% endif %} required>
    </div>


    <div class="mb-3">
      <label class="form-label">Genero do filme</label>
      <select name="genero" required>
        <option value="">Selecione o Gênero</option>
        <option value="acao">Ação</option>
        <option value="animacao">Animação</option>
        <option value="aventura">Aventura</option>
        <option value="comedia">Comédia</option>
        <option value="documentario">Documentário</option>
        <option value="drama">Drama</option>
        <option value="ficcao-cientifica">Ficção Científica</option>
        <option value="horror">Horror</option>
        <option value="musical">Musical</option>
        <option value="romance">Romance</option>
        <option value="suspense">Suspense</option>
        <option value="guerra">Guerra</option>
        </select>
    </div>


    <div class="mb-3">
      <label class="form-label">Duração(minutos):</label>
      <input type="number" class="form-control" name="duracao" {% if filme %} value="{{filme.filme_duracao}}" {% endif %} required>
    </div>


    <div class="mb-3">
      <label class="form-label">Sinopse:</label>
      <input type="text" class="form-control" name="sinopse" {% if filme %} value="{{filme.filme_sinopse}}" {% endif %} required>
    </div>

    <div class="mb-3">
      <label class="form-label">Poster</label>
      <input type="file" class="form-control" name="poster">
      {% if filme and filme.filme_poster %}
        <img src="{{ filme.filme_poster }}" alt="Poster do Filme" style="max-width: 200px;">
      {% endif %}
    </div>

    <button  type="submit" class="btn btn-primary"> {% if filme %} Salvar {% else %} Cadastrar {% endif %}</button>

  </form>
</div>

src/templates/index.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Lista de Filmes</title>
  <link rel="stylesheet" href="../static/css/listar_filme.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>

  <div class="container">

    {% if escolha %}
    <!-- formulario adicionar cliente -->
    <div id="form-cliente"
         c-container="{{ url_for('{{escolha}}') }}"></div>

    {% else %}
    <div id="lista_filmes"
         c-container="{{ url_for('filmes.listar_filmes') }}"></div>

    {% endif %}
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <script src="{{ url_for('static', filename='js/cru.js') }}"></script>
</body>
</html>

src/templates/index_filmes.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Lista de Filmes</title>
  <link rel="stylesheet" href="../static/css/listar_filme.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<div class="fundo">
  <div c-container="{{ url_for('filmes.listar_filmes') }}"></div>
  <ul class="lista-filmes-Criar">
    <div id="index-filmes" class="container">
      <li>
        <img class="Poster" src="../static/Image/Play.png" alt="Criar"> 
      </li>
      <button class="btn btn-primary" 
c-get="{{ url_for('filmes.form_create_filme') }}"
c-target="#index-filmes">Criar</button>
  
    </div>
  </ul>
</div>

    
      <script src="../static/js/script.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <script src="{{ url_for('static', filename='js/cru.js') }}"></script>
</body>
</html>

src/templates/listar_filmes.html
  <h1 style="text-align: center; color: white;text-shadow:0px 1px 10px white;">Lista de Filmes</h1>
  
  <ul class="lista-filmes" >
    {% for filme in filmes %}
    <div>
    <li>
      <!--<div class="Poster">{{filme.filme_poster}}</div>-->
      <img class="Poster" src="../static/Image/exemplo1.jpg" alt="Filme's"> 
    </li>
     
    <li class="conteudo">
      <h2>{{ filme.filme_nome }}</h2>
      
      <div class="simbolos">
        {{filme.filme_genero}}
      </div>
      <hr>
      <p>{{filme.filme_data}}</p>{{filme.filme_sinopse }}</p><p>{{filme.filme_duracao}}</p>
      <button class="btn btn-success"
            c-get="{{ url_for('filmes.form_editar_filme', filme_id = filme.id) }}"
            c-target="#index-filmes" >Editar</button>

    <button class="btn btn-danger"
            c-delete="{{ url_for('filmes.delete_filme', filme_id = filme.id) }}"
            c-remove-closest="li">Deletar</button>
    </li>
  </div>
    {% endfor %}
    
    </ul>
    

  

  
 